export const APPEND_QUESTION = 'APPEND_QUESTION';
export const SET_MAX_QUESTIONS = 'SET_MAX_QUESTIONS';
export const SET_QUESTION_ARRAY = 'SET_QUESTION_ARRAY';
export const SET_EXAM_TIMER = 'SET_EXAM_TIMER';
export const SET_EXAM_RANDOMNESS = 'SET_EXAM_RANDOMNESS';
export const SET_EXAM_ANSWER_KEY = 'SET_EXAM_ANSWER_KEY';
export const SET_EXAM_ANSWER_KEY_AT = 'SET_EXAM_ANSWER_KEY_AT';
export const SET_EXAM_QUESTION_INDEX = 'SET_EXAM_QUESTION_INDEX';
export const DELETE_EXAM_QUESTION_INDEX = 'DELETE_EXAM_QUESTION_INDEX';
export const REMOVE_TIME_OBJECT = 'REMOVE_TIME_OBJECT';
export const SET_WHO_CAN_SEE_OBJECT = 'SET_WHO_CAN_SEE_OBJECT';
export const SET_EXAM_QUESTIONS_STUDENT = 'SET_EXAM_QUESTIONS_STUDENT';
export const CHANGE_PREVIEW = 'CHANGE_PREVIEW';
export const CHANGE_QUESTION_OPTIONS = 'CHANGE_QUESTION_OPTIONS'


export const SET_CREATE_EXAM_ARRAY = 'SET_CREATE_EXAM_ARRAY';
export const APPEND_QUESTION_EXAM = 'APPEND_QUESTION_EXAM';
// user actions
export const SET_USER = 'SET_USER';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_TAB = 'SET_TAB';
export const SET_TOTAL_POINTS = 'SET_TOTAL_POINTS';
export const SET_NEW_QUESTION_ARRAY = 'SET_NEW_QUESTION_ARRAY';
export const SET_ASSIGNED_FOR = 'SET_ASSIGNED_FOR';
export const SET_SPECIFIC_STUDENTS = 'SET_SPECIFIC_STUDENTS';
export const SET_STUDENTS = 'SET_STUDENTS';
export const SET_NAVIGATION = 'SET_NAVIGATION';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_NEW_ANSWER_QUESTION_ARRAY = 'SET_NEW_ANSWER_QUESTION_ARRAY';
export const SET_STARTING_AT = 'SET_STARTING_AT';
export const SET_ENDING_AT = 'SET_ENDING_AT';
export const SET_EXAM_TITLE = 'SET_EXAM_TITLE';
export const AUTHENTICATE = 'AUTHENTICATE';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
// course actions
export const SET_CLASSROOM_ID = 'SET_CLASSROOM_ID';
export const SET_COURSE_ID = 'SET_COURSE_ID';
export const SET_COURSE_INFO = 'SET_COURSE_INFO';
export const SET_COURSE_ANNOUNCEMENTS = 'SET_COURSE_ANNOUNCEMENTS';
export const SET_COURSE_CLASSMATES = 'SET_COURSE_CLASSMATES';
export const SET_COURSE_EXAMS = 'SET_COURSE_EXAMS';
// question action
export const SET_TMP_ID = 'SET_TMP_ID'
export const SET_POINTS = 'SET_POINTS'
export const SET_WHO_CAN_SEE = 'SET_WHO_CAN_SEE'
export const SET_QUESTION_TYPE = 'SET_QUESTION_TYPE'
export const SET_QUESTION_TEXT = 'SET_QUESTION_TEXT'
export const SET_IS_ACTIVE = 'SET_IS_ACTIVE'
export const SET_OPTIONS = 'SET_OPTIONS'
export const SET_ANSWER_KEY = 'SET_ANSWER_KEY'
