export const APPEND_QUESTION = 'APPEND_QUESTION';
export const SET_MAX_QUESTIONS = 'SET_MAX_QUESTIONS';
export const SET_QUESTION_ARRAY = 'SET_QUESTION_ARRAY';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_ROLE_ID = 'SET_ROLE_ID';